### PR TITLE
finalizes draft of project one for review...

### LINKED ISSUE #3: Refactor project 1 (only as needed)
Chris, I see you've made some commits on this already. Holler if you need any help.

### PR DESCRIPTION
**Pull request by chrislkeller**
This should wrap up a refactor of project one and close #3, at least until any feedback is provided by @tommeagher, @hbillings, @kevinschaul, @katiepark, @rdmurphy or @esagara...

Streamlined things quite a bit and really focused on fundamentals found in the tutorial. It will be walking folks through the tutorial for the most part, but that might be an OK thing.

Parts 2 and 3 get into downloading a file and looping through its contents.

A couple thoughts:

* Where is appropriate to have the global vs. local variable discussion
* How to handle division
* Python 2 vs. Python 3 will come up

### CODE REVIEW

**Comment by tommeagher** [comment]
Chris,
This looks great. I'd say go ahead and merge it in, though if anyone has other feedback or advice, please raise your hand.

To your question on variable scoping I wonder what others think. Is there a way to introduce scoping without sending the students down a path of fear and confusion?

As far as Python 2 vs 3, I think we can mention it in passing. I don't know that folks would get much out of that debate other than knowing it exists. 

What did you have in mind about division?

Tom

**Comment by rdmurphy** [comment]
Hey folks! Thanks for pulling this all together Chris! It's awesome.

Some feedback:

#### 2 vs. 3
It's tough. I think these days most people still using Python 2 are doing so because of either:

- actual compatibility reasons
- it still works, I know it works, so why change it?

So I think saying anything too suggestive (Python 3 is too new! Don't trust it!) would be misleading. ([A good read on this.](http://docs.python-guide.org/en/latest/starting/which-python/#the-state-of-python-2-vs-3)) Ideally, we actually **do** want people to start moving to Python 3. It's easier for beginners than people using it, honestly.

The biggest argument I'd make here – OSX Yosemite ships with Python 2.7. So it's still good enough there. If we say anything, I say we say we're teaching Python 2 because it's what we're all comfortable with and use day-to-day, and it's what's installed by default on Macs. But we should encourage folks to check out Python 3 when they're ready. Just no fear mongering. :)

#### Python spacing
When it comes to spacing of Python code, I think it'd be best to just say the convention is to use 4 spaces. Like most languages, Python won't care as long as you're consistent, but I really cannot remember the last time I came across code that didn't do the 4 space convention. (And when I did, it was someone using tabs, not spaces.) For the sake of teaching good practices/making it easy to collaborate with other Python programmers, we may not want to leave that too ambiguous.

#### Scoping
I'd say save the scoping discussion until you describe how functions work. I think if we explain it before then it could get confusing. If you wait for functions, then you can give examples of setting variables inside and outside of a function and do the classic "what do you think `x` would equal after this?"

#### Strings
I'd say synonymous with `characters` instead of words.

#### Unicode
I'm torn on unicode. I know it's important (and something we all battle), but for a beginner it seems like a strange thing to have to grok (and I feel like some days I'm *still* trying to grok it). I know it comes up in later lessons, but I'd almost say we don't go into that at all for the first lesson.

#### Lists
The term `compound data type` feels a little wonky to me. Is it a necessary term for explaining what lists are (even if Python uses it in its docs)? I'd vote for using the terms `collection` or  `collection of things` instead of `container of values` or `bucket`, too. Also torn on explaining mutability unless we give examples of non-mutable things, or examples of why things would ever not be mutable.

#### Is vs. ==
May be worth stressing the difference here. `==` is for comparing values – is `2` equal to `2`? `is` is for comparing whether the two items are the same *exact* thing. So:

```python
x = {'hello': 'world'}
y = x

print x is y
# True
```
I only bring this up because I used to think they were identical to each other. *Sometimes* `is` works for numbers (because of Python weirdness), but it won't always, especially when the number is larger.

Could be too much for lesson 1 though.

#### Opening files and `with`
In the final example, we show two different ways to deal with opened files. The output file is `open()`ed and `close()`ed, but the input file uses `with`. This may be on purpose, but the `with` method is ideal for both operations. It's built in closing once the thread ends is really important to preventing lost of data via failure to close out files (or if your program crashes). If we show both ways on purpose, I think we should stress the `with` method is the preferred/better option.

**Comment by tommeagher** [comment]
All excellent points, Ryan, particularly regarding Python 3 and is vs ==. This is really helpful. Thanks!

**Comment by chrislkeller** [comment]
Thanks all... 

Made adjustments and tweaks, and can make more if other feedback comes in. If not, this is ready to go.

**Pull request merged**
