### PR TITLE
Preparing PyCAR for NICAR 17

### PR DESCRIPTION
**Pull request by tommeagher**
This proposed branch closes a number of tickets in this repo:
* #30 - it ports all the existing lesson code to Python 3.6
* #38 - It incorporates @zufanka's pandas lesson in, adding it to the end of day 2.
* #39 - it converts all the lessons to use Jupyter notebooks, with a shell notebook for each part in the ```projectn/``` dir and a completed file in the ```completed/``` dir.

It updates the schedule of the day in the README and the takehome basic exercise.

Would @chrislkeller, @elainewong, @esagara, @robroc, @hbillings, @zufanka  please pull this branch, examine it and test it? Any and all feedback would be good. Feel free to push additional commits to this branch. Suggestions from others watching the repo or teachers in past years is also welcome.

If it's OK with everyone and I hear no objections by Feb. 23, I'll merge into master and we'll be good to go.

### CODE REVIEW

**Comment by tommeagher** [comment]
In https://github.com/ireapps/pycar/blob/py3/completed/JSON_to_CSV_notebook_complete.ipynb, do we even need to use ```unicodecsv```? In Python3, shouldn't ```csv``` suffice?

**Comment by robroc** [comment]
Indeed, @tommeagher. Python 3's innate unicode support makes `unicodecsv` obsolete. It's actually the main reason I moved to 3.

**Comment by tommeagher** [comment]
@robroc that doesn't sound right. Where are you seeing that? Are you sure it's in the ```py3``` branch and not ```master```?

**Comment by robroc** [comment]
@tommeagher Oops, I was looking in master. I'm still a GitHub noob when it comes to collaborating.

**Comment by zufanka** [comment]
@tommeagher I have already started a review, did some small adjustments to some projects and rewritten the debugging intermezzo in a jupyter notebook.
How does it work with a review then? Shall I just push to origin master as usual after pulling?

**Comment by tommeagher** [comment]
@zufanka, if you pulled the Py3 branch, push the changes back to this branch (git push origin py3) and post a note on this thread when you're done so we can all take a look at the updates. After we've reviewed the changes here, I'll merge this branch into master.

**Comment by zufanka** [comment]
Reviewed!
Run all the code, minor things adapted in the completed sheets, debugging intermezzo rewritten and adapted the pandas notebook a bit.
See you all in a week or so !

**Comment by tommeagher** [comment]
@zufanka this is all great. Thank you for the thorough review. One question about the debugging exercise: do we need to add lxml to the requirements.txt so the beautifulsoup parser will work?

Otherwise, I think this is ready to merge into the master branch.

**Comment by zufanka** [comment]
yes, otherwise pandas will give a warning.
You can also erase it and leave for the students to debug :)
Either way is fine by me.

**Comment by zufanka** [comment]
Oh, sorry I misunderstood. Hm.. I don't know but I guess it should be fine!
I think it's a part of bs itself

**Comment by tommeagher** [comment]
@zufanka, ahhh, I think that's my mistake. I'll doublecheck and merge.

**Comment by tommeagher** [comment]
@zufanka, it looks like you do have to have lxml installed to use that parser with bs4. I've added it to the requirements.txt file. IRE may not have time to add it to the machines in time, in which case, it'll be part of the debugging exercise. Otherwise, this all looks good, and I'm merging this branch into master now.

Thanks, all!

**Pull request merged**
